service: visao-computacional  # Nome do serviço consolidado

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9  # Atualizado para a versão Python que você deseja
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:*:*:*  

    - Effect: Allow
      Action:
        - rekognition:DetectFaces
        - rekognition:DetectLabels
      Resource: "*"  

    - Effect: Allow
      Action: s3:GetObject
      Resource: arn:aws:s3:::photogrupo3/*  

    - Effect: Allow
      Action:
        - bedrock:InvokeModel
        - bedrock:ListModels
      Resource: "*"  

  environment:
    BUCKET_NAME: "${env:BUCKET_NAME, 'photogrupo3'}"  
    FOLDER_NAME: "${env:FOLDER_NAME, 'default-folder'}"  

functions:
  visionHealthCheck:
    handler: handlers.handler_health
    events:
      - httpApi:
          path: /
          method: get

  visionGetDescriptionV1:
    handler: handlers.handler_v1_description
    events:
      - httpApi:
          path: /v1
          method: get

  visionGetDescriptionV2:
    handler: handlers.handler_v2_description
    events:
      - httpApi:
          path: /v2
          method: get

  visionDetectFaces:
    handler: handlers.handler_face
    timeout: 30
    events:
      - httpApi:
          path: /v1/vision
          method: post

  visionDetectPets:
    handler: handlers.handler_pet
    timeout: 30
    events:
      - httpApi:
          path: /v2/vision
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: false
    fileName: ../requirements.txt  

package:
  exclude:
    - utils/**
    - .gitignore
    - .git/**               # Ignora todos os arquivos e pastas do diretório .git
    - .vscode/**            # Ignora todos os arquivos e pastas do diretório .vscode
